// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20240227204028_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Pariz",
                            Country = "Francuska",
                            Description = "Veliki toranj.",
                            Name = "Ajfelov toranj"
                        },
                        new
                        {
                            Id = 2,
                            City = "Rim",
                            Country = "Italija",
                            Description = "Trg iz doba antickog Rima.",
                            Name = "Forum"
                        },
                        new
                        {
                            Id = 3,
                            City = "Beograd",
                            Country = "Srbija",
                            Description = "Srednjevekovna tvrdjava.",
                            Name = "Kalemegdan"
                        },
                        new
                        {
                            Id = 4,
                            City = "Kragujevac",
                            Country = "Srbija",
                            Description = "Muzej posvecen zrtvama drugog svetskog rata.",
                            Name = "Muzej 21. Oktobar"
                        },
                        new
                        {
                            Id = 5,
                            City = "Milano",
                            Country = "Italija",
                            Description = "Jedna od najvecih katedrala evrope.",
                            Name = "Katedrala Duomo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
